// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6_lYT6Q1Ge6a7THHO0bWVmGPce-iO5NQ',
    appId: '1:257683660833:web:182445c25b7dce4fd1c360',
    messagingSenderId: '257683660833',
    projectId: 'honnyapp',
    authDomain: 'honnyapp.firebaseapp.com',
    storageBucket: 'honnyapp.firebasestorage.app',
    measurementId: 'G-3E1CJHH014',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrripI-aL8ih-yxlBCZACOieodwlf6nRI',
    appId: '1:257683660833:android:a07256d4db41b525d1c360',
    messagingSenderId: '257683660833',
    projectId: 'honnyapp',
    storageBucket: 'honnyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYaQ5RriS4rbdJijBiMIbqgQhwvCC9nAs',
    appId: '1:257683660833:ios:d5dbabc64ca9694dd1c360',
    messagingSenderId: '257683660833',
    projectId: 'honnyapp',
    storageBucket: 'honnyapp.firebasestorage.app',
    iosBundleId: 'com.example.honnyapp',
  );
}
